export enum BookingStatus {
  PENDING = 0,
  APPROVED = 1,
  DECLINED = 2,
  ONGOING = 3,
  MODIFIED_BY_STUDENT = 4,
  CANCELED_BY_STUDENT = 5,
  CANCELED_BY_TUTOR = 6,
  EXPIRED = 7,
  READY_TO_REVIEW = 8,
  END = 9,
}
