import { SubjectTypes } from '../constant/subjectTypes';
import { DetailTypes } from '../constant/tableNames';

export default [
  {
    id: '1_subject',
    subjectName: 'Accounting',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/1_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '2_subject',
    subjectName: 'Add. Mathematics',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/2_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '3_subject',
    subjectName: 'Biology',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/3_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '4_subject',
    subjectName: 'Biology HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/4_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '5_subject',
    subjectName: 'Biology SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/5_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '6_subject',
    subjectName: 'Business Studies',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/6_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '7_subject',
    subjectName: 'Chemistry',
    subjectType: SubjectTypes.POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/7_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '8_subject',
    subjectName: 'Chemistry HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/8_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '9_subject',
    subjectName: 'Chemistry SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/9_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '10_subject',
    subjectName: 'Computer Science',
    subjectType: SubjectTypes.POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/10_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '11_subject',
    subjectName: 'Computer Science HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/11_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '12_subject',
    subjectName: 'Computer Science SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/12_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '13_subject',
    subjectName: 'Design Technology HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/13_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '14_subject',
    subjectName: 'Design Technology SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/14_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '15_subject',
    subjectName: 'Economics',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/15_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '16_subject',
    subjectName: 'Economics HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/16_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '17_subject',
    subjectName: 'Economics SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/17_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '18_subject',
    subjectName: 'English (First Language)',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/18_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '19_subject',
    subjectName: 'English B HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/19_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '20_subject',
    subjectName: 'English B SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/20_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '21_subject',
    subjectName: 'English Literature',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/21_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '22_subject',
    subjectName: 'English Literature HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/22_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '23_subject',
    subjectName: 'English Literature SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/23_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '24_subject',
    subjectName: 'French B HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/24_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '25_subject',
    subjectName: 'French B SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/25_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '26_subject',
    subjectName: 'French Literature HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/26_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '27_subject',
    subjectName: 'French Literature SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/27_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '28_subject',
    subjectName: 'Further Mathematics',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/28_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '29_subject',
    subjectName: 'Geography',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/29_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '30_subject',
    subjectName: 'Global Politics HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/30_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '31_subject',
    subjectName: 'Global Politics SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/31_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '32_subject',
    subjectName: 'History',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/32_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '33_subject',
    subjectName: 'History HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/33_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '34_subject',
    subjectName: 'History SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/34_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '35_subject',
    subjectName: 'ICT',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/35_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '36_subject',
    subjectName: 'Mathematics',
    subjectType: SubjectTypes.POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/36_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '37_subject',
    subjectName: 'Mathematics (Analysis and Approaches HL)',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/37_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '38_subject',
    subjectName: 'Mathematics (Analysis and Approaches SL)',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/38_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '39_subject',
    subjectName: 'Mathematics: (Applications and Interpretation HL)',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/39_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '40_subject',
    subjectName: 'Mathematics: (Applications and Interpretation SL)',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/40_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '41_subject',
    subjectName: 'Physics',
    subjectType: SubjectTypes.POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/41_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '42_subject',
    subjectName: 'Physics HL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/42_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '43_subject',
    subjectName: 'Physics SL',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/43_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
  {
    id: '44_subject',
    subjectName: 'Psychology',
    subjectType: SubjectTypes.NON_POPULAR,
    imageUrl: 'https://studtors-assets.s3.amazonaws.com/subject-images/44_subject.png',
    detailType: DetailTypes.SUBJECT.toString(),
  },
];
